--------------------
-- Table category
--------------------
CREATE TABLE "category" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT UNIQUE NOT NULL, -- le nom de la catégorie est obligatoire et unique

    -- created_at et updated_at sont des champs techniques pour connaître la date de création et de mise à jour d'un enregistrement
    -- TIMESTAMPTZ est un type de données PostgreSQL qui stocke une date et une heure avec le fuseau horaire
    -- NOW() est une fonction PostgreSQL qui retourne la date et l'heure actuelles
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

-------------------
-- Table country
-------------------
CREATE TABLE "country" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT UNIQUE NOT NULL, -- le nom du pays est obligatoire et unique

    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

-------------------
-- Table coffee
-------------------
CREATE TABLE "coffee" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,                                   -- le nom du café est obligatoire
    "description" TEXT,                                     -- la description du café est facultative
    "reference" CHAR(9) UNIQUE NOT NULL,                    -- la référence du café est obligatoire et doit faire 9 caractères
    "price_per_kg" DECIMAL NOT NULL,                        -- le prix par kilogramme est obligatoire               
    "available" BOOLEAN NOT NULL DEFAULT false,             -- la disponibilité du café est obligatoire et par défaut à false             
    "country_id" INTEGER NOT NULL REFERENCES country(id),   -- clé étrangère vers la table country   

    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

-------------------
-- Table coffee_category
-- table de jointure entre coffee et category
-- Cette table permet de gérer la relation many-to-many entre coffee et category
-------------------
CREATE TABLE "coffee_category" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- on aurait pu utiliser à la place une clé primaire composite sur coffee_id et category_id
    "coffee_id" INTEGER NOT NULL REFERENCES coffee(id),        -- clé étrangère vers la table coffee
    "category_id" INTEGER NOT NULL REFERENCES category(id)     -- clé étrangère vers la table category
);